### ISSUE TITLE
Failed to use libclang on widows.

### ISSUE THREAD

**Issue by UrielCh** [aapoalas/libclang-deno#4]
I'm trying to use libclang with on windows and that fail:

## setup:
in an admin powershell, install llvm with chocolatey:
```powershell
choco install llvm
```
prepare a test script:

```typescript
import * as libclang from "https://deno.land/x/libclang@1.0.0-beta.3/mod.ts";
import { walkSync } from "https://deno.land/std@0.171.0/fs/walk.ts";
import {
  dirname,
  fromFileUrl,
  join,
} from "https://deno.land/std@0.171.0/path/mod.ts";

const __dirname = dirname(fromFileUrl(import.meta.url));
const index = new libclang.CXIndex();
const sourceDirectory = join(__dirname, "..", "vips-dev-8.14");
const headers = walkSync(sourceDirectory, { exts: [".h"] });
let allHeaders: string[] = []
for (const header of headers) {
  allHeaders.push(header.path)
}

allHeaders = allHeaders.filter(a => a.endsWith('ffi.h'))

for (const allHeader of allHeaders) {
  const tu = index.parseTranslationUnit(allHeader, [
    `-I${sourceDirectory}`,
  ]);

  tu.getCursor().visitChildren((cursor) => {
    console.log(`${cursor.getKindSpelling()}: ${cursor.getSpelling()}`);
    return libclang.CXChildVisitResult.CXChildVisit_Recurse;
  });
}
```

Then try to run it from a powershell terminal:
```powershell
$Env:LIBCLANG_PATH = "C:\Program Files\LLVM\bin\libclang.dll"
echo Global Env Path point to $Env:LIBCLANG_PATH
deno run --unstable -A .\build\generator2.ts
```

Deno lib access activity viewed by `Procmon`

![image](https://user-images.githubusercontent.com/6543761/215393358-de782019-05a5-4bee-8d1c-677fe2800512.png)

Deno never try to load libs next to `C:\Program Files\LLVM\bin\`

the output error is:
```bash
error: Uncaught Error: Could not open library: The specified module could not be found.

  libclang = Deno.dlopen(
```

that the same issue as: [issue 17466](https://github.com/denoland/deno/issues/17466)

for ref list of file in the LLVM bin directory:
```
C:\Program Files\LLVM\bin> ls *.dll


    Directory: C:\Program Files\LLVM\bin


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        02/12/2020     05:30          12240 api-ms-win-core-console-l1-1-0.dll
-a----        02/12/2020     05:30         XXX     39 other api-*.dll
-a----        02/12/2020     05:30          12240 api-ms-win-crt-utility-l1-1-0.dll
-a----        12/07/2022     10:51         317864 concrt140.dll
-a----        16/11/2022     12:19       91027968 libclang.dll
-a----        16/11/2022     12:20      112992768 liblldb.dll
-a----        16/11/2022     12:16         745984 libomp.dll
-a----        16/11/2022     12:20       82832896 LLVM-C.dll
-a----        16/11/2022     12:16       81676288 LTO.dll
-a----        12/07/2022     10:51         566704 msvcp140.dll
-a----        12/07/2022     10:51          23944 msvcp140_1.dll
-a----        12/07/2022     10:51         186800 msvcp140_2.dll
-a----        12/07/2022     10:51          57264 msvcp140_atomic_wait.dll
-a----        12/07/2022     10:51          21424 msvcp140_codecvt_ids.dll
-a----        16/11/2022     12:20         220672 Remarks.dll
-a----        02/12/2020     05:31        1035728 ucrtbase.dll
-a----        12/07/2022     10:51          98224 vcruntime140.dll
-a----        12/07/2022     10:51          37256 vcruntime140_1.dll
```

**Comment by UrielCh** [comment]
same test in an Ubuntu VM:
```bash
sudo apt-get install -y libclang1-14
dpkg-query -L libclang1-14
export LIBCLANG_PATH=/usr/lib/llvm-14/lib/libclang.so.1
deno run --unstable -A test.ts
```
failed with `error: Uncaught Error: Could not open library: Could not open library: /usr/lib/llvm-14/lib/libclang.so/libclang.so.13: cannot open shared object file: Not a directory`

and 
```bash
sudo apt-get install -y libclang1-14
dpkg-query -L libclang1-14
export LIBCLANG_PATH=/usr/lib/llvm-14/lib/
deno run --unstable -A test.ts
```
properly load the lib

**Comment by UrielCh** [comment]
After some more test, can you double check, in your doc your write:

> This variable can either contain the direct path to a `libclang` shared library or a path to the directory containing the shared library.

I think that currently `LIBCLANG_PATH` must point to the directory, not the lib file.

**Comment by UrielCh** [comment]
the first par or the issue was generate using LLVM 15.X.X

I'm now making test with the correct version:
```bash
choco install --version 14.0.6 llvm
```

**Comment by aapoalas** [comment]
beta.3 had a bug where the library wouldn't properly handle `LIBCLANG_PATH` pointing to the lib file. With beta.6 it should be fine either way. It is generally more correct to use the directory path (eg. Rust libclang bindings only accept directory path) but it has been useful for me to check between versions by directly pointing to the .so file I want to load. Thus, the support is there.

There is an issue with how the loading is done, however... Your error message of `libclang.so/libclang.so.13` failing to be opened tells me that I've done a bad job :)

For Windows, I think the issue is indeed the same deno bug you linked, ie. that the Windows DLL search order doesn't actually look to load dependent DLLs from the directory where the dependee is in. This might be fixable by changing the PATH environment variable so that it also points to the directory of the library, ie. same as `LIBCLANG_PATH` if you point it to a directory.

**Comment by UrielCh** [comment]
thx,
have now a new issue:
`error: Uncaught Error: Failed to register symbol clang_uninstall_llvm_fatal_error_handler: Could not obtain symbol from the library: The specified procedure could not be found. (os error 127)`
I used the chocolatey V 14.0.6 of llvm.

That strange, `clang_uninstall_llvm_fatal_error_handler` looks not available in the windows build.

**Comment by UrielCh** [comment]
On windows `libclang.dll` 14.0.6 contains 390 export symbols, and clang_uninstall_llvm_fatal_error_handler is not one of them.

on linux:
```bash
nm -D --demangle /usr/lib/llvm-14/lib/libclang-14.so.1  | wc -l
1380
```

```bash
nm -D --demangle /usr/lib/llvm-14/lib/libclang-14.so.1  | grep clang_uninstall_llvm_fatal_error_handler
00000000004f5ed0 T clang_uninstall_llvm_fatal_error_handler@@LLVM_13
```

Now I'm trying to find the lost exports.

**Comment by UrielCh** [comment]
Yeah, I made it work on windows.

The windows version contains less symbols, but the main ones are still here.

Can I Open a PR ?

**Comment by aapoalas** [comment]
Sure

**Comment by UrielCh** [comment]
https://github.com/aapoalas/libclang_deno/pull/6

**Comment by UrielCh** [comment]
Tested code to export vips-dev-8.14 function signatures:

```typescript
//console.log('LIBCLANG_PATH', Deno.env.get('LIBCLANG_PATH'));

// import * as libclang from "https://deno.land/x/libclang@1.0.0-beta.6/mod.ts";
import * as libclang from "../../libclang_deno/lib/mod.ts";
import { walkSync } from "https://deno.land/std@0.171.0/fs/walk.ts";
import {
  dirname,
  fromFileUrl,
  join,
} from "https://deno.land/std@0.171.0/path/mod.ts";

// Deno.env.set('LIBCLANG_PATH', 'C:\\Program Files\\LLVM\\lib\\libclang.dll')
// console.log('LIBCLANG_PATH', Deno.env.get('LIBCLANG_PATH'));

// node style __dirname
const __dirname = dirname(fromFileUrl(import.meta.url));
const index = new libclang.CXIndex();
const sourceDirectory = join(__dirname, "..", "vips-dev-8.14");
const headers = walkSync(sourceDirectory, { exts: [".h"] });
let allHeaders: string[] = []
//const allHeaders: { [key: string]: { source: string; code: string } } = {};
for (const header of headers) {
  allHeaders.push(header.path)
}

allHeaders = allHeaders.filter(a => a.endsWith('ffi.h'))

for (const allHeader of allHeaders) {
  const tu = index.parseTranslationUnit(allHeader, [
    `-I${sourceDirectory}`,
  ]);

  tu.getCursor().visitChildren((cursor) => {
    console.log(`${cursor.getKindSpelling()}: ${cursor.getSpelling()}`);
    return libclang.CXChildVisitResult.CXChildVisit_Recurse;
  });
}
```


output:
```bash
C:\1\libvips-4-deno> deno run --unstable -A .\build\generator2.ts
TypedefDecl: ffi_arg
TypedefDecl: ffi_sarg
EnumDecl: ffi_abi
EnumConstantDecl: FFI_FIRST_ABI
IntegerLiteral:
EnumConstantDecl: FFI_WIN64
EnumConstantDecl: FFI_GNUW64
EnumConstantDecl: FFI_LAST_ABI
EnumConstantDecl: FFI_DEFAULT_ABI
DeclRefExpr: FFI_WIN64
TypedefDecl: ffi_abi
EnumDecl: ffi_abi
EnumConstantDecl: FFI_FIRST_ABI
....
```

**Comment by UrielCh** [comment]
I'm preparing a new PR, including only testing code.

**Comment by UrielCh** [comment]
All done,

Have a nice day
